// Package porttraffic defines the stable accounting boundary for the optional
// Port Traffic module. It deals only in kernel byte counters; payloads and
// process identity never enter this package.
package porttraffic

import (
	"errors"
	"fmt"
	"regexp"
	"sort"
	"time"
)

type Protocol string
type Direction string
type TupleView string
type Path string

const (
	TCP Protocol = "tcp"
	UDP Protocol = "udp"

	Inbound  Direction = "inbound"
	Outbound Direction = "outbound"

	OriginalTuple   TupleView = "original"
	TranslatedTuple TupleView = "translated"

	// LocalPath uses the input/output hooks for traffic addressed to or
	// generated by this host. ForwardedPath uses the forward hook for routed,
	// bridge, container, or tunnel traffic that does not traverse input/output
	// as a locally terminated packet.
	LocalPath     Path = "local"
	ForwardedPath Path = "forwarded"
)

var interfacePattern = regexp.MustCompile(`^[A-Za-z0-9_.:-]{1,64}$`)

// Scope is one non-additive accounting key. Port always means a local service
// port in the selected tuple view; it never means a remote destination used
// by an outbound client.
type Scope struct {
	ID        string    `json:"id"`
	Protocol  Protocol  `json:"protocol"`
	Interface string    `json:"interface"`
	LocalPort uint16    `json:"local_port"`
	Direction Direction `json:"direction"`
	Tuple     TupleView `json:"tuple"`
	Path      Path      `json:"path,omitempty"`
}

func (s Scope) Validate() error {
	if !interfacePattern.MatchString(s.ID) {
		return errors.New("scope id must be a safe 1..64 character identifier")
	}
	if s.Protocol != TCP && s.Protocol != UDP {
		return errors.New("protocol must be tcp or udp")
	}
	if !interfacePattern.MatchString(s.Interface) {
		return errors.New("interface must be a safe 1..64 character name")
	}
	if s.LocalPort == 0 {
		return errors.New("local_port must be 1..65535")
	}
	if s.Direction != Inbound && s.Direction != Outbound {
		return errors.New("direction must be inbound or outbound")
	}
	if s.Tuple != OriginalTuple && s.Tuple != TranslatedTuple {
		return errors.New("tuple must be original or translated")
	}
	if s.Path != "" && s.Path != LocalPath && s.Path != ForwardedPath {
		return errors.New("path must be local or forwarded")
	}
	return nil
}

func ValidateScopes(scopes []Scope) error {
	if len(scopes) == 0 || len(scopes) > 256 {
		return errors.New("scope count must be 1..256")
	}
	seenID := make(map[string]struct{}, len(scopes))
	seenKey := make(map[string]string, len(scopes))
	for _, scope := range scopes {
		if err := scope.Validate(); err != nil {
			return fmt.Errorf("scope %q: %w", scope.ID, err)
		}
		if _, exists := seenID[scope.ID]; exists {
			return fmt.Errorf("duplicate scope id %q", scope.ID)
		}
		seenID[scope.ID] = struct{}{}
		path := scope.Path
		if path == "" {
			path = LocalPath
		}
		key := fmt.Sprintf("%s\x00%s\x00%d\x00%s\x00%s\x00%s", scope.Protocol, scope.Interface, scope.LocalPort, scope.Direction, scope.Tuple, path)
		if previous, exists := seenKey[key]; exists {
			return fmt.Errorf("scopes %q and %q select the same counter", previous, scope.ID)
		}
		seenKey[key] = scope.ID
	}
	return nil
}

// Counter is an absolute kernel counter. Generation changes whenever owned
// rules are recreated, so consumers never interpret a reload as a rollover.
type Counter struct {
	ScopeID    string    `json:"scope_id"`
	Bytes      uint64    `json:"bytes,string"`
	Packets    uint64    `json:"packets,string"`
	Generation string    `json:"generation"`
	ObservedAt time.Time `json:"observed_at"`
}

type Delta struct {
	ScopeID    string    `json:"scope_id"`
	Bytes      uint64    `json:"bytes,string"`
	Packets    uint64    `json:"packets,string"`
	From       time.Time `json:"from"`
	To         time.Time `json:"to"`
	Continuity string    `json:"continuity"`
	Reason     string    `json:"reason,omitempty"`
}

// Tracker converts absolute counters to deltas without inventing traffic
// before enablement or across counter decreases/rule reloads.
type Tracker struct{ previous map[string]Counter }

func NewTracker() *Tracker { return &Tracker{previous: make(map[string]Counter)} }

func (t *Tracker) Observe(counters []Counter) ([]Delta, error) {
	if len(counters) > 256 {
		return nil, errors.New("counter snapshot exceeds limit")
	}
	ordered := append([]Counter(nil), counters...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].ScopeID < ordered[j].ScopeID })
	seen := make(map[string]struct{}, len(ordered))
	result := make([]Delta, 0, len(ordered))
	for _, current := range ordered {
		if !interfacePattern.MatchString(current.ScopeID) || current.Generation == "" || len(current.Generation) > 128 || current.ObservedAt.IsZero() {
			return nil, errors.New("invalid counter snapshot")
		}
		if _, duplicate := seen[current.ScopeID]; duplicate {
			return nil, fmt.Errorf("duplicate counter for scope %q", current.ScopeID)
		}
		seen[current.ScopeID] = struct{}{}
		previous, exists := t.previous[current.ScopeID]
		delta := Delta{ScopeID: current.ScopeID, To: current.ObservedAt, Continuity: "uncertain", Reason: "coverage-start"}
		if exists {
			delta.From = previous.ObservedAt
			switch {
			case !current.ObservedAt.After(previous.ObservedAt):
				return nil, fmt.Errorf("counter time did not advance for scope %q", current.ScopeID)
			case current.Generation != previous.Generation:
				delta.Reason = "rule-reload"
			case current.Bytes < previous.Bytes || current.Packets < previous.Packets:
				delta.Reason = "counter-reset"
			default:
				delta.Bytes = current.Bytes - previous.Bytes
				delta.Packets = current.Packets - previous.Packets
				delta.Continuity = "complete"
				delta.Reason = ""
			}
		}
		t.previous[current.ScopeID] = current
		result = append(result, delta)
	}
	return result, nil
}
